[package]
name = "vmdl"
version = "0.1.0"
edition = "2021"
exclude = ["data"]

[dependencies]
arrayvec = "0.7.2"
thiserror = "1.0.37"
static_assertions = "1.1.0"
bitflags = "1.3.2"
itertools = "0.10.5"
tracing = "0.1.37"
bytemuck = { version = "1.12.3", features = ["derive"] }
cgmath = "0.18.0"

[dev-dependencies]
three-d = "0.10.2"
miette = { version = "4.7.1", features = ["fancy"] }
criterion = "0.3"
iai = "0.1"

[[bench]]
name = "parse"
harness = false

[[bench]]
name = "iai"
harness = false
